[package]
name = "mack"
version = "1.3.0"
edition = "2021"
authors = ["Chris Down <chris@chrisdown.name>"]
description = "An opinionated, fast music organiser."
repository = "https://github.com/cdown/mack"
readme = "README.md"
keywords = ["music", "audio", "organiser", "tagging", "mp3"]
categories = ["command-line-utilities", "filesystem"]
license = "MIT"
rust-version = "1.65.0"

[dependencies]
clap = { version = "4.2.2", features = ["derive"] }
walkdir = "2.3.3"
regex = "1.7.3"
anyhow = "1.0.70"
id3 = "1.7.0"
funcfmt = "0.2.0"
once_cell = "1.17.1"
cow-utils = "0.1.2"
rayon = "1.7.0"

[target.'cfg(target_family = "unix")'.dependencies]
libc = "0.2.141"

[target.'cfg(target_family = "windows")'.dependencies]
winapi = "0.3.9"
