[package]
name = "mack"
version = "1.2.1"
authors = ["Chris Down <chris@chrisdown.name>"]
description = "An opinionated, fast music organiser."
homepage = "https://github.com/cdown/mack"
readme = "README.md"
keywords = ["music", "audio", "organiser", "tagging", "mp3"]
license = "Unlicense"

[dependencies]
clap = { version = "3", features = ["cargo"] }
walkdir = "2"
lazy_static = "1"
regex = "1"
taglib = "1"
libc = "0.2"

[profile.release]
lto = true
codegen-units = 1
debug = true
