[package]
name = "mack"
version = "0.1.0"
authors = ["Chris Down <chris@chrisdown.name>"]
description = "An opinionated, fast music organiser."
homepage = "https://github.com/cdown/mack"
readme = "README.md"
keywords = ["music", "audio", "music organiser", "tagging", "mp3"]
license = "Public Domain"

[dependencies]
clap = "*"
ignore = "*"
lazy_static = "*"
regex = "*"
taglib = { git = "https://github.com/ebassi/taglib-rust", rev = "781c4f431639c10868fea020dfb0eb8d74954653"}
